### ISSUE TITLE
Move to urllib 3

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-transformers#13]
Use https://github.com/shazow/urllib3

**Comment by Cerfoglg** [comment]
@VincenzoFerme For now we are using pypy2, so we need to use urllib2 for Python 2.7. We will use urllib3 when we can use pypy3, if we will.

**Comment by VincenzoFerme** [comment]
@Cerfoglg why? The documentation says:

`Tested on Python 2.6+, Python 3.2+, and PyPy, with 100% unit test coverage.`

**Comment by Cerfoglg** [comment]
@VincenzoFerme We use the Minio API, this is no longer necessary
