### ISSUE TITLE
Update pyspark cassandra to use Cassandra 3.0 when available

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/data-transformers#16]
As it stands, Cassandra 3.0 is not supported by the pyspark cassandra connector. Cassandra 3.0 would be ideal to use, thanks to its new features like materialized views, so once support for Cassandra 3.0 is added to pyspark cassandra it would be good to implement it.

An issue has already been opened by a different user on their Github: https://github.com/TargetHolding/pyspark-cassandra/issues/69

**Comment by VincenzoFerme** [comment]
@Cerfoglg it seems that a new version supporting Cassandra 3 will be published soon: https://github.com/TargetHolding/pyspark-cassandra/issues/69#issuecomment-196227139

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, we now have support for Cassandra 3.0
