### ISSUE TITLE
Define a Functional Testing Methodology for the scripts

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-transformers#29]
See https://github.com/benchflow/analysers/issues/26

**Comment by VincenzoFerme** [comment]
Catch known errors (e.g., https://github.com/benchflow/spark-tasks-sender/issues/38) that cannot be avoided and retry the test in case you get this error.

**Comment by VincenzoFerme** [comment]
@Cerfoglg update it referencing to #56 and just describe the delta.

**Comment by Cerfoglg** [comment]
@VincenzoFerme Should probably close this one as well
