### ISSUE TITLE
Fix Build Issues

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-transformers#64]
The build has an issue related to `Alluxio`: https://travis-ci.org/benchflow/data-transformers/builds/132672028

If it's about the Travis job that gets canceled, read the following: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out. Then apply the same to other repos that possibly have the same issue, e.g.,

**Comment by Cerfoglg** [comment]
@VincenzoFerme It wasn't related to Alluxio, it's just Travis timing out. I've since changed it to have travis retrying if taking too long
